### ISSUE TITLE
Consider reading /dev/random instead of using SecureRandom

### ISSUE THREAD

**Issue by samdunne** [robertomiranda/has_secure_token#9]
SecureRandom uses /dev/urandom which is non blocking (fantastic!), however when the entropy pool becomes small enough it becomes possible to guess the resulting number produced.

Reading /dev/random will be a much more secure way of generating this.

The only possible downside is that /dev/random is blocking

**Comment by jimtreadway** [comment]
Arguments for just using **/dev/urandom** instead of **/dev/random**:

- http://www.2uo.de/myths-about-urandom/
- http://sockpuppet.org/blog/2014/02/25/safely-generate-random-numbers/

**Comment by robertomiranda** [comment]
@samdunne @jimtreadway really interesting discussion, but since this is a back-port  I think that would be better to move the discussion http://github.com/rails/rails, otherwise ["The security is in terms of its random generation. See SecureRandom"](https://github.com/rails/rails/pull/18217#issuecomment-69435324)
